config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, only: [:index, :new, :create]
  resources :events do
    collection do
      get 'index_my'
    end
    member do
      post 'add_player'
      delete 'decline'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :game
  belongs_to :user
  has_many :user_events, dependent: :destroy
  geocoded_by :place
  after_validation :geocode, if: :will_save_change_to_place?

  validates :date, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:date, :details, :place],
    associated_against: {
      game: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :events, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [:name],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook, :github]

  mount_uploader :photo, PhotoUploader
  has_many :events
  has_many :user_events, dependent: :destroy

  def self.from_facebook(auth)
    where(facebook_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.remote_photo_url = auth.info.image
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.from_github(auth)
    where(github_id: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.remote_photo_url = auth.info.image
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates_uniqueness_of :event, scope: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :add_player]
  def index

    if params[:query].present?
      @events = Event.global_search("%#{params[:query]}%")
    else
      @events = Event.all
      @events = @events.order(:date)
    end


    # @events = Event.geocoded
    # @markers = @events.map do |event|
    #   {
    #     lat: event.latitude,
    #     lng: event.longitude
    #   }
    # end

  end

  def index_my
    @events = Event.where("user_id = ?", current_user)
    @events = @events.order(:date)
  end

  def show
    @markers = [{ lat: @event.latitude, lng: @event.longitude, infoWindow: render_to_string(partial: "info_window", locals: { place: @event.place }) }]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_events)
    @event.user = current_user
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def add_player
    @invit = UserEvent.new
    @invit.event = @event
    @invit.user = current_user
    if @invit.save
      redirect_to event_path, :notice => 'You are added to the game'
    else
      redirect_to event_path, :alert => 'Something go wrong!'
    end
  end

  def decline
    @invit = UserEvent.where("user_id = ? AND event_id = ?", current_user, params[:id])
    if !@invit.empty?
      if @invit[0].delete
        redirect_to event_path, :alert => 'You have decline'
      else
        render "index", :alert => 'Something go wrong!'
      end
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def params_events
    params.require(:event).permit(:date, :details, :place, :game_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      @games = Game.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @games = Game.all
    end
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params_games)
    if @game.save
      redirect_to games_path
    else
      render :new
    end
  end

  private

  def params_games
    params.require(:game).permit(:name, :rules, :photo, :player_max)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    if user_signed_in?
      redirect_to events_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_facebook(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentification
    else
      session['devise.facebook'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  def github
    @user = User.from_github(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentification
    else
      session['devise.github'] = request.env['omniauth.auth']
      raise
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_info_window.html.erb
<p><%= @event.place %></p>

app/views/events/index.html.erb
<h1 class="text-primary font-weight-bold text-center" style="padding-top: 20px;">Les parties à rejoindre</h1>
<div class="container">
  <div class="row">
    <% @events.each do |event| %>
    <div class="col-md-4 col-lg-3 my-3">
      <div class="card-trip">
        <%= link_to event_path(event) do %>
        <%= cl_image_tag event.game.photo %>
        <div class="card-trip-infos">
          <div>
            <h2><%= event.game.name %></h2>
            <p><%= event.details %></p>
            <% i = 0 %>
            <% event.user_events.each do |invit| %>
              <% i += 16 %>
              <%= cl_image_tag invit.user.photo, class:"card-trip-invit avatar-bordered", style:"left: #{i}px" %>
          <%end %>
          <p class="font-weight-bold text-right"> <%= event.place %> </p>
          </div>
          <h3 class="card-trip-pricing border border-primary rounded p-1 mx-1"><%= event.date.time.to_formatted_s(:short) %></h3>
          <%= cl_image_tag event.user.photo, class:"card-trip-user avatar-bordered" %>
        </div>
        <% end %>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/events/index_my.html.erb
<h1 class="text-primary font-weight-bold text-center" style="padding-top: 20px;">Mes parties</h1>
<div class="container">

<h2 class="text-primary font-weight-bold">
Vous avez <%= pluralize @events.size, "event" %> prévus
</h2>
  <% if @events.blank? %>
  <div class="row align-items-center px-3">
    Organisez votre première partie.
    <%= link_to new_event_path, class: "nav-link" do %>
      <i class="fas fa-plus-circle fa-2x"></i>
    <% end %>
  </div>
  <% else %>
  <div class="row">
    <% @events.each do |event| %>
    <div class="col-md-4 col-lg-3 my-3">
      <div class="card-trip">
        <%= link_to event_path(event) do %>
        <%= cl_image_tag event.game.photo %>
        <div class="card-trip-infos">
          <div>
            <h2><%= event.game.name %></h2>
            <p><%= event.details %></p>
            <% i = 0 %>
            <% event.user_events.each do |invit| %>
            <% i += 16 %>
            <%= cl_image_tag invit.user.photo, class:"card-trip-invit avatar-bordered", style:"left: #{i}px" %>
            <%end %>
          </div>
          <h2 class="card-trip-pricing"><%= event.date.strftime("on %d %m %Y at %I:%M%p") %></h2>
        </div>
        <% end %>
      </div>
    </div>
    <%end%>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div  class="p-3 mb-2">

  <h1 class="text-primary font-weight-bold text-center">Tu souhaites créer une nouvelle partie ?</h1>
  <p class="text-primary text-center">Très simple entre les informations demandées</p>
  <div class= "mx-auto" style="width: 500px">
    <%= simple_form_for [@event] do |f| %>
    <%= f.input :date, html5: true %>

    <%= f.input :details, placeholder: "Info supplémentaires"%>

    <%= f.input :place, placeholder: "Entre l'adresse du lieu"  %>
    <%= f.association :game %>
    <%= f.submit "Ajouter la partie", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>

</div>

app/views/events/show.html.erb
<h1 class="text-primary font-weight-bold text-center" style="padding-top: 20px;">Partie à rejoindre</h1>

<div class="container">
  <div class="row ">
    <div class="col-lg-4">
      <div class="card-trip">
        <%= cl_image_tag @event.game.photo %>
        <div class="card-trip-infos" style="height:300px;">
          <div class="info-show d-flex flex-column justify-content-between ">
            <h2><%= @event.game.name %></h2>
            <p>Rules: <%= @event.game.rules %></p>
            <h5>Player max: <%=@event.game.player_max %></h5>

          </div>

        </div>

      </div>
    </div>

    <div class="col-lg-8">
      <div
        id="map"
        style="width: 100%;
        height: 500px; margin-bottom: 20px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

      </div>
    </div>
  </div>
  <div class="row">
    <div class="card-trip col-lg-12">
        <div class="card-trip-infos">

          <%= cl_image_tag @event.user.photo, class:"card-trip-user-show avatar-bordered" %>
          <% i = 0 %>
            <% @event.user_events.each do |invit| %>
              <% i += 16 %>
              <%= cl_image_tag invit.user.photo, class:"card-trip-user-show avatar-bordered", style:"left: #{i}px" %>
          <%end %>

        </div>
        <div class="d-flex justify-content-between p-2">
<div>
            <h2><%= @event.place %></h2>
            <p><%= @event.details %></p>
            </div>


      <h2 class="card-trip-pricing border border-primary rounded p-1 mx-1"><%= @event.date.time.to_formatted_s(:short) %></h2>
      <div>
              <button class="btn btn-outline-primary"> <%= link_to "S'inscrire", add_player_event_path, method: :post %></button>
      <button class="btn btn-outline-danger"><%= link_to "Decline", decline_event_path, method: :delete %></button>
            </div>
      </div>
      </div>
    </div>

</div>
  </div>

app/views/games/index.html.erb
<h1 class="titre">Games List</h1>
<div class="container">
  <div class="row">
    <% @games.each do |game| %>
    <div class="col-lg-6 my-3">
      <div class="card-product">
        <%= cl_image_tag game.photo %>
        <div class="card-product-infos">
          <div class="d-flex justify-content-between">
            <h2><%= game.name %></h2>
            <h4>Max Players: <%= game.player_max%></h4>
          </div>
          <p><%= game.rules %></p>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/games/new.html.erb
<%= simple_form_for [@game] do |f| %>
  <%= f.input :name %>
  <%= f.input :rules %>
  <%= f.input :player_max %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add a game", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Game :Hover - Is in da place 😜</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>

    <div class="page">
      <%= yield %>
    </div>
    <%= render 'shared/footer'%>
    <%= render 'shared/flashes'%>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/featured/?board-games);">
  <div class="container">
    <h1><strong>Game</strong> <span id="banner-typed-text"></span></h1>
    <p>Change your live and play for life!</p>
    <%=link_to events_path do %>
      <button class="btn btn-flat" href="#">Play now</button>
    <%end%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "gg_logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active px-3 ">
        <%= link_to root_path, class: "nav-link home" do %>
          <i class="fas fa-home fa-2x"></i>
        <% end %>
      </li>

      <li class="nav-item active px-3">
        <%= link_to index_my_events_path, class: "nav-link mes-parties"  do %>
          <i class="fas fa-dice fa-2x"></i>
        <% end %>
      </li>

      <li class="nav-item active px-3">
        <%= link_to new_event_path, class: "nav-link ta-partie" do %>
          <i class="fas fa-plus-circle fa-2x"></i>
        <% end %>
      </li>

      <li class="nav-item active px-3">
        <%= link_to games_path, class: "nav-link jeux" do %>
          <i class="fas fa-chess-knight fa-2x"></i>
        <% end %>
      </li>


      <li>
        <% path = controller_name == "events" ? events_path : games_path %>
        <%= form_tag path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control" , placeholder: "search" %>
        <% end %>
      </li>


      <li class="nav-item px-3">
        <% if !user_signed_in? %>
        <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>

      <li class="nav-item dropdown">
        <% if user_signed_in? && current_user.photo.file %>
          <%= cl_image_tag current_user.photo , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "non_existing_id.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profil", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>